version: '3'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend-container
    volumes:
      - ./dist:/usr/share/nginx/html  # 挂载前端静态文件
      - ./nginx.conf:/etc/nginx/nginx.conf  # 挂载自定义 Nginx 配置
      - /etc/letsencrypt:/etc/letsencrypt  # 挂载 SSL 证书
      - ./certbot/www:/var/www/certbot  # Certbot 用于自动验证
    ports:
      - "80:80"
      - "443:443"  # 添加 HTTPS 端口
    restart: always
